"""Single-cell MatrixMarket pseudobulk loader + scrnaseq concordance entry point.

Real files only, via pytest tmp_path; no mocks, no tool execution, no network.
Pure stdlib fixtures (gzip). Mirrors the fixture style of test_count_concordance.py.
"""

import gzip

import pytest

from contig.verification.count_concordance import parse_count_matrix
from contig.verification.sc_count_concordance import (
    ScMatrixError,
    evaluate_sc_count_concordance,
    load_mtx_pseudobulk,
    load_sc_matrix,
)


def _write_text(path, text, gz):
    if gz:
        with gzip.open(path, "wt") as fh:
            fh.write(text)
    else:
        path.write_text(text)
    return path


def _write_triplet(
    d,
    genes,
    cells,
    counts,
    *,
    gene_axis="rows",
    features_gz=False,
    barcodes_gz=False,
    mtx_gz=False,
    write_barcodes=True,
    comment=False,
):
    """Render a 10x-style triplet (matrix.mtx, features.tsv, barcodes.tsv).

    - genes: list of feature specs; a str -> single-column feature line, a tuple
      -> tab-joined (id, name, type) with column 1 the gene id.
    - cells: list of barcode strings.
    - counts: list of (gene_index, cell_index, value) triplets, 1-based, where
      gene_index/cell_index are logical (independent of orientation). With
      gene_axis="rows" genes are mtx rows; with "cols" the matrix is transposed so
      the same counts must yield the same per-gene pseudobulk totals.
    Returns the matrix.mtx path.
    """
    # features.tsv
    feat_lines = []
    for g in genes:
        feat_lines.append("\t".join(g) if isinstance(g, tuple) else str(g))
    feat_name = "features.tsv.gz" if features_gz else "features.tsv"
    _write_text(d / feat_name, "".join(l + "\n" for l in feat_lines), features_gz)

    # barcodes.tsv
    if write_barcodes:
        bc_name = "barcodes.tsv.gz" if barcodes_gz else "barcodes.tsv"
        _write_text(d / bc_name, "".join(c + "\n" for c in cells), barcodes_gz)

    # matrix.mtx
    if gene_axis == "rows":
        nrows, ncols = len(genes), len(cells)
    else:
        nrows, ncols = len(cells), len(genes)
    mtx_lines = ["%%MatrixMarket matrix coordinate integer general"]
    if comment:
        mtx_lines.append("% generated by a synthetic test fixture")
    mtx_lines.append(f"{nrows} {ncols} {len(counts)}")
    for gi, ci, val in counts:
        r, c = (gi, ci) if gene_axis == "rows" else (ci, gi)
        mtx_lines.append(f"{r} {c} {val}")
    mtx_name = "matrix.mtx.gz" if mtx_gz else "matrix.mtx"
    mtx_path = _write_text(
        d / mtx_name, "".join(l + "\n" for l in mtx_lines), mtx_gz
    )
    return mtx_path


def _write_dense_counts(path, mapping):
    """A one-sample-column dense pseudobulk TSV, no header."""
    path.write_text("".join(f"{g}\t{v}\n" for g, v in mapping.items()))
    return path


# --- load_mtx_pseudobulk: orientation ----------------------------------------


def test_genes_as_rows_sum(tmp_path):
    # 3 genes x 2 cells, genes are rows. Pseudobulk = row sum across cells.
    mtx = _write_triplet(
        tmp_path,
        genes=["geneA", "geneB", "geneC"],
        cells=["cell1", "cell2"],
        counts=[(1, 1, 10), (1, 2, 5), (2, 1, 3), (3, 2, 7)],
    )

    assert load_mtx_pseudobulk(mtx) == {"geneA": 15.0, "geneB": 3.0, "geneC": 7.0}


def test_genes_as_cols_transposed_same_totals(tmp_path):
    # Same logical counts, matrix transposed (genes are columns) -> same totals.
    mtx = _write_triplet(
        tmp_path,
        genes=["geneA", "geneB", "geneC"],
        cells=["cell1", "cell2"],
        counts=[(1, 1, 10), (1, 2, 5), (2, 1, 3), (3, 2, 7)],
        gene_axis="cols",
    )

    assert load_mtx_pseudobulk(mtx) == {"geneA": 15.0, "geneB": 3.0, "geneC": 7.0}


def test_gzipped_triplet(tmp_path):
    mtx = _write_triplet(
        tmp_path,
        genes=["geneA", "geneB", "geneC"],
        cells=["cell1", "cell2"],
        counts=[(1, 1, 10), (1, 2, 5), (2, 1, 3), (3, 2, 7)],
        features_gz=True,
        barcodes_gz=True,
        mtx_gz=True,
    )

    assert load_mtx_pseudobulk(mtx) == {"geneA": 15.0, "geneB": 3.0, "geneC": 7.0}


def test_banner_and_comment_lines_skipped(tmp_path):
    # The %%MatrixMarket banner + a % comment line must be skipped; the first
    # non-comment line is the dimension line.
    mtx = _write_triplet(
        tmp_path,
        genes=["geneA", "geneB"],
        cells=["cell1"],
        counts=[(1, 1, 4), (2, 1, 6)],
        comment=True,
    )

    assert load_mtx_pseudobulk(mtx) == {"geneA": 4.0, "geneB": 6.0}


def test_multicol_features_keyed_by_column_one(tmp_path):
    # 10x features.tsv is (id, name, type); the gene id is column 1.
    mtx = _write_triplet(
        tmp_path,
        genes=[
            ("ENSG01", "Alpha", "Gene Expression"),
            ("ENSG02", "Beta", "Gene Expression"),
        ],
        cells=["cell1"],
        counts=[(1, 1, 4), (2, 1, 6)],
    )

    assert load_mtx_pseudobulk(mtx) == {"ENSG01": 4.0, "ENSG02": 6.0}


def test_single_col_features_use_sole_token(tmp_path):
    mtx = _write_triplet(
        tmp_path,
        genes=["geneA", "geneB"],
        cells=["cell1"],
        counts=[(1, 1, 4), (2, 1, 6)],
    )

    assert load_mtx_pseudobulk(mtx) == {"geneA": 4.0, "geneB": 6.0}


def test_missing_barcodes_sibling_raises(tmp_path):
    mtx = _write_triplet(
        tmp_path,
        genes=["geneA", "geneB"],
        cells=["cell1"],
        counts=[(1, 1, 4), (2, 1, 6)],
        write_barcodes=False,
    )

    with pytest.raises(ScMatrixError):
        load_mtx_pseudobulk(mtx)


def test_ambiguous_orientation_raises(tmp_path):
    # dims match neither axis (3 genes, 2 cells, but dim line 5x5) -> ScMatrixError.
    _write_triplet(
        tmp_path,
        genes=["geneA", "geneB", "geneC"],
        cells=["cell1", "cell2"],
        counts=[(1, 1, 1)],
    )
    # Overwrite the mtx with a mismatched dimension line.
    (tmp_path / "matrix.mtx").write_text(
        "%%MatrixMarket matrix coordinate integer general\n5 5 1\n1 1 1\n"
    )

    with pytest.raises(ScMatrixError):
        load_mtx_pseudobulk(tmp_path / "matrix.mtx")


def test_square_orientation_is_ambiguous(tmp_path):
    # genes == cells (square) -> both orientations match -> ambiguous -> raise.
    mtx = _write_triplet(
        tmp_path,
        genes=["geneA", "geneB"],
        cells=["cell1", "cell2"],
        counts=[(1, 1, 1), (2, 2, 1)],
    )

    with pytest.raises(ScMatrixError):
        load_mtx_pseudobulk(mtx)


# --- load_sc_matrix sniff router ---------------------------------------------


def test_sniff_routes_mtx_to_loader(tmp_path):
    mtx = _write_triplet(
        tmp_path,
        genes=["geneA", "geneB"],
        cells=["cell1"],
        counts=[(1, 1, 4), (2, 1, 6)],
    )

    assert load_sc_matrix(mtx) == {"geneA": 4.0, "geneB": 6.0}


def test_sniff_routes_dense_tsv_to_parse_count_matrix(tmp_path):
    mapping = {"geneA": 10.0, "geneB": 20.0}
    tsv = _write_dense_counts(tmp_path / "pseudobulk.tsv", mapping)

    assert load_sc_matrix(tsv) == parse_count_matrix(tsv) == mapping


# --- evaluate_sc_count_concordance: gated entry point ------------------------


def _mtx_pseudobulk(d, mapping, *, gene_axis="rows"):
    """A single-cell triplet whose per-gene pseudobulk equals `mapping`."""
    d.mkdir(parents=True, exist_ok=True)
    genes = list(mapping)
    counts = [(i + 1, 1, mapping[g]) for i, g in enumerate(genes)]
    return _write_triplet(d, genes=genes, cells=["cell1"], counts=counts,
                          gene_axis=gene_axis)


def test_concordant_pair_passes(tmp_path):
    mapping = {f"gene{i:02d}": (i + 1) * 100 for i in range(12)}
    primary = _mtx_pseudobulk(tmp_path / "a", mapping)
    (tmp_path / "b").mkdir()
    second = _mtx_pseudobulk(tmp_path / "b", dict(mapping))

    results = {r.check: r for r in
               evaluate_sc_count_concordance(primary, second, assay="scrnaseq")}

    assert results["spearman_concordance"].status == "pass"
    assert results["spearman_concordance"].value == 1.0


def test_divergent_pair_warns(tmp_path):
    a_map = {f"gene{i:02d}": (i + 1) * 100 for i in range(12)}
    b_map = {f"gene{i:02d}": (12 - i) * 100 for i in range(12)}
    primary = _mtx_pseudobulk(tmp_path / "a", a_map)
    (tmp_path / "b").mkdir()
    second = _mtx_pseudobulk(tmp_path / "b", b_map)

    results = {r.check: r for r in
               evaluate_sc_count_concordance(primary, second, assay="scrnaseq")}
    spearman = results["spearman_concordance"]

    assert spearman.status == "warn"
    assert spearman.value is not None and spearman.value < 0.90


def test_too_few_shared_genes_unverified(tmp_path):
    mapping = {f"gene{i:02d}": (i + 1) * 100 for i in range(5)}
    primary = _mtx_pseudobulk(tmp_path / "a", mapping)
    (tmp_path / "b").mkdir()
    second = _mtx_pseudobulk(tmp_path / "b", dict(mapping))

    results = {r.check: r for r in
               evaluate_sc_count_concordance(primary, second, assay="scrnaseq")}

    assert results["spearman_concordance"].status == "unverified"
    assert results["spearman_concordance"].value is None


def test_second_matrix_dense_tsv_sniffed(tmp_path):
    # Second matrix supplied as a dense pseudobulk TSV (sniff router path).
    mapping = {f"gene{i:02d}": (i + 1) * 100 for i in range(12)}
    primary = _mtx_pseudobulk(tmp_path / "a", mapping)
    second = _write_dense_counts(tmp_path / "second.tsv", dict(mapping))

    results = {r.check: r for r in
               evaluate_sc_count_concordance(primary, second, assay="scrnaseq")}

    assert results["spearman_concordance"].status == "pass"


def test_non_scrnaseq_assay_returns_empty(tmp_path):
    mapping = {f"gene{i:02d}": (i + 1) * 100 for i in range(12)}
    primary = _mtx_pseudobulk(tmp_path / "a", mapping)
    (tmp_path / "b").mkdir()
    second = _mtx_pseudobulk(tmp_path / "b", dict(mapping))

    assert evaluate_sc_count_concordance(primary, second, assay="rnaseq") == []


def test_primary_missing_sibling_one_unverified(tmp_path):
    # primary .mtx present but its barcodes sibling is missing -> exactly ONE
    # sc_count_concordance UNVERIFIED (not [], not a crash, never a false pass).
    (tmp_path / "a").mkdir()
    primary = _write_triplet(
        tmp_path / "a",
        genes=[f"gene{i:02d}" for i in range(12)],
        cells=["cell1"],
        counts=[(i + 1, 1, (i + 1) * 100) for i in range(12)],
        write_barcodes=False,
    )
    second = _write_dense_counts(
        tmp_path / "second.tsv",
        {f"gene{i:02d}": (i + 1) * 100 for i in range(12)},
    )

    results = evaluate_sc_count_concordance(primary, second, assay="scrnaseq")

    assert len(results) == 1
    assert results[0].check == "sc_count_concordance"
    assert results[0].status == "unverified"
    assert results[0].value is None
    assert "matrix.mtx" in results[0].message
